### ISSUE TITLE
Error using cast_dtm command

### ISSUE THREAD

**Issue by dsdesrosiers** [juliasilge/tidytext#19] opened 2016-08-04 15:45 UTC
Used tidytext to parse support case subjects into words...then grouped by case number and word to count,. Ended up with a tibble that looks like this sample

 A tibble: 38,923 x 3
   CaseNumber     word     n
        <int>    <chr> <int>
1    20695703   backup     1
2    20695703 catalogs     1

When I try to execute subject.freq %>% cast_dtm(CaseNumber, word, n) I get this error

Error in as.lazy_dots(.dots) : 
  argument ".dots" is missing, with no default

I downloaded the latest dev version of tidytext but that does not alleviate the issue. Any help is appreciated.

On Twitter as @NevilleLeoniers

**Comment by juliasilge** [comment] 2016-08-04 23:07
I just went through the example with the Associated Press data in the [vignette here](https://cran.r-project.org/web/packages/tidytext/vignettes/tidying_casting.html) and it seems to be still working. What happens if you try this, with the example data?

```
data("AssociatedPress", package = "topicmodels")
ap_td <- tidy(AssociatedPress)
# the output here ap_td should look very very similar to your tibble above
ap_tdm %>% cast_dtm(document, term, count)
```

Do you get the same error as on your data?

One thought -- do you have the latest version of dplyr? It's possible we should require a later version of dplyr and don't right now.

**Comment by dsdesrosiers** [comment] 2016-08-05 01:51
Julia -

Thanks for the response and suggestion.

Your sample code works, my code still fails. I downloaded the latest dplyr... no help. I've done the unlikely dumb stuff like cast the integer column to a double and rename the column 'n' to 'count'.  I wrote out the data and there is nothing obviously wrong with it in terms of unexpected characters.  I also tested a couple subsets using the words for a single case and I get the same result.

The data I am working with can be a bit unpredictable in that it's free form text entered by our support agents which may contain software error codes.  Is there any cleansing steps I should try before I run the unnest_tokens command?

Danielle

**Comment by juliasilge** [comment] 2016-08-05 02:07
Could it be the column `CaseNumber`? When it tries to make a DocumentTermMatrix, it needs a column of documents (case numbers, for you) in integer form (like 1, 2, 3...) to use as matrix indices. What data type and distribution are the values in `CaseNumber`? Will the function be able to use those values as matrix indices to make a DocumentTerm Matrix?

(Actually, now that I wrote this, I am not sure if it's right. Let me check...)

**Comment by juliasilge** [comment] 2016-08-05 02:21
I don't think I am right that you need to pass an integer, but I am wondering if that is where the problem is, in converting the data you have in `CaseNumber` into row numbers for the matrix indices. (You can see where this is done [right about here](https://github.com/juliasilge/tidytext/blob/3c21b61f1cf0aa9f477cd562a637ec9959ad38da/R/sparse_casters.R#L25). What kind of data is being kept in `CaseNumber`? What type is it? Factor? How is it distributed?

**Comment by dsdesrosiers** [comment] 2016-08-05 13:55
So, to expedite this, I just replaced the case numbers (which are literally the number of the case in our CRM) with 1, 2, 3 in the .CSV before reading it into the initial data frame. Same result. 

But, then I wrote the data to a .CSV, re-read the same data and now it works. I have to set this aside for now and I don't want to take any more of your time at the moment since I have a workaround. It's very strange though - I am not doing anything particularly novel with the data processing. 

Please let me know if you'd like me to supply some sample data/code.  Thanks for your time and energy.

**Comment by juliasilge** [comment] 2016-08-05 14:03
If you can make a small, reproducible example (i.e. not 40,000 lines) that errors, that would certainly be great. If not, best of luck! I'll let you close this issue if you feel like you are good for now.

**Comment by dgrtwo** [comment] 2016-08-05 14:26
The problem is that `subject.freq` is grouped- I'm able to reproduce the error with:

```
mtcars %>% group_by(gear) %>% cast_dtm(cyl, am, mpg)
```

I think `cast_dtm` should ignore groups- if @juliasilge agrees I'll push a fix. (In the meantime an easier workaround than writing to a CSV and reading would be using `ungroup()` first).

Thanks for the report!

**Comment by juliasilge** [comment] 2016-08-05 14:35
Ah, I didn't think of that! Yes, that sounds very sensible; I think `cast_dtm` (`cast_sparse_`?) should ignore groups.

**Closed as completed** 2016-08-05 14:45 UTC

**Comment by dsdesrosiers** [comment] 2016-08-05 21:15
I had actually ungrouped and was still getting the issue, but I will try the updated version. If I am still getting the error I will supply some sample data and my R code. I just need identify a set of data that reproduced the error and keeps me in line with my employers data guidelines. 

Thanks to both of you for helping with this issue.

**Comment by dsdesrosiers** [comment] 2016-08-05 21:19
It worked!!! Happy weekend!
