### ISSUE TITLE
error when I try to extract the beta matrix of an LDA function from topicmodels package

### ISSUE THREAD

**Issue by Eli0203** [juliasilge/tidytext#101] opened 2018-02-23 12:54 UTC
lda <- LDA(dtm.new, k = 8) # find 8 topics
ap_topics <- tidytext::tidy(lda, matrix = "beta")

###Error
Error in as.data.frame.default(x) : 
  cannot coerce class "structure("LDA_VEM", package = "topicmodels")" to a data.frame
In addition: Warning message:
In tidy.default(lda, matrix = "beta") :
  No method for tidying an S3 object of class LDA_VEM , using as.data.frame

**Comment by juliasilge** [comment] 2018-02-23 14:28
Hello! Thanks so much for your interest in tidytext. Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it. Please help me help you!

If you've never heard of a reprex before, start by reading ["What is a reprex"](https://github.com/tidyverse/reprex#what-is-a-reprex), and follow the advice further down that page.

One immediate thought I have is that [another user saw this error when saving .Rdata files between sessions](https://stackoverflow.com/questions/48765936/using-tidytext-and-broom-but-not-finding-tidier-for-lda-vem/), which is not good practice.

**Comment by juliasilge** [comment] 2018-04-02 03:10
Hello there, @Eli0203 ! Let me know if/when you are able to put together a reproducible example to help diagnose your problem. I'm going to close this issue for now. Good luck!

**Closed as completed by juliasilge** 2018-04-02 03:10 UTC

**Comment by rbno3** [comment] 2018-08-13 15:05
Hi julia,

I have encountered the same problem during learning Text Mining with R. Originally, it works fine but suddenly it doesn't work when I try to run the code below.

library(dplyr)
library(stringr)
library(gutenbergr)
library(tidyr)
library(topicmodels)
library(tidytext)
gt4<- gutenberg_download(c(7439,14300,37787,3708),meta_fields = "title")

#transfering normal books to LDA: tidy->cast_dtm->lda
gt4_chapter<-gt4%>%
  group_by(title)%>%
  mutate(chapter=
           cumsum(str_detect(text,regex("^chapter ",ignore_case = TRUE))))%>%
  ungroup()%>%
  filter(chapter>0)%>%
  unite(document,title,chapter,sep="_")%>% #create document
  unnest_tokens(word,text)%>%
  anti_join(stop_words)%>%
  count(document,word,sort = TRUE)%>%
  ungroup()

gt4_chapter_lda<-gt4_chapter%>%
  cast_dtm(document,word,n)%>%
  LDA(k=4,control = list(seed=1234))

#analyze topic words
gt4_chapter_lda%>%
  tidy(matrix="beta")%>%
  group_by(topic)%>%
  top_n(10,beta)%>%
  ungroup()%>%
  mutate(term=reorder(term,beta))%>%
  ggplot(aes(term,beta,fill=factor(topic)))+
  geom_col()+
  facet_wrap(~topic,scales = "free")+
  coord_flip()

error:
Error in as.data.frame.default(x) : 
  cannot coerce class ‘structure("LDA_VEM", package = "topicmodels")’ to a data.frame
In addition: Warning message:
In tidy.default(., matrix = "beta") :
  No method for tidying an S3 object of class LDA_VEM , using as.data.frame

**Comment by rbno3** [comment] 2018-08-13 15:06
thanks in advance :)

**Comment by erobique** [comment] 2018-08-14 07:34
Tried deleting your .Rhistory / .RData file? Worked for me.

**Comment by rbno3** [comment] 2018-08-14 07:56
Thanks Erobique. I think I have saw your comments in stackflow yesterday and I have tried.
It didn't work for me.
However, I **restart my computer**rand tried again it work.

**Comment by juliasilge** [comment] 2018-08-14 20:39
Thank so much for using tidytext, @rbno3! This is an error that a couple of users have run into (as you have noticed) but I just have not been able to reproduce it in order to see what's happening. As best as I can tell, it is something to do with an R environment or `.Rdata` file or something "behind the scenes" like that being stored between sessions.

If you are able to put together a reproducible example to help diagnose this problem, please do share it! In the meantime, you might consider a [workflow where you don't save your workspace between sessions](http://stat545.com/block002_hello-r-workspace-wd-project.html#workspace-and-working-directory), because it can be a source of problems.

**Comment by chrismainey** [comment] 2018-12-14 13:38
@juliasilge Don't know if this is any use, but I've had this issue too.  It occurred when I loaded an .RData file with saved LDA models in.  But if I remove them from the environment, restart R, and reload the LDAs from .RDS files instead, the tidy method works fine.

**Comment by juliasilge** [comment] 2018-12-14 18:08
@chrismainey This is becoming basically a KNOWN ISSUE at this point 😕 and I am sorry for your frustration. As best as I can tell, there is a bug in the topicmodels package, possibly related to S4 method registration.

That is really interesting that using `.RDS` fixed the problem for you; thank you for sharing that.

**Comment by rpyhong** [comment] 2019-01-02 11:59
@juliasilge 
Error: No augment method for objects of class LDA_VEM  << that is what problem ??

code 
```
augment(df.lda , data = df.dtm)
```

**Comment by juliasilge** [comment] 2019-01-02 15:58
@RPyLnSl Thanks for your interest in tidytext! Can you make a small reproducible example that shows how you got this error? I need more information than this to be able to figure out what's going on. 

If you haven't ever made a reproducible example (a reprex) before, check out [this explanation of what one is](https://www.tidyverse.org/help/) and this [list of guidelines on how to make a good one](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html).
